
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    # restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=familymoney
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - service_network

  webserver:
    image: nginx:alpine
    container_name: nginx
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.familymoney.rule=Host(`familymoney.store`) || Host(`www.familymoney.store`)"
        - "traefik.http.routers.familymoney.entrypoints=websecure"
        - "traefik.http.routers.familymoney.tls=true"
        - "traefik.http.routers.familymoney.tls.certresolver=myresolver"
        - "traefik.http.services.familymoney.loadbalancer.server.port=80"
        # Middleware definitions (moved here)
        - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\\.(.*)"
        - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}"
        - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"           
    # restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - service_network

  postgres:
    image: postgres:16
    container_name: postgres
    # restart: unless-stopped
    environment:
      POSTGRES_DB: familymoney
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - service_network

volumes:
  pgdata:

networks:
  service_network:
    external: true
