services:
  react-app:
    build: .
    container_name: familymoney
    ports:
      - "5173:5173"
    volumes:
      # mount your code
      - .:/app:delegated
      # use a named volume for node_modules so it gets initialized
      - node_modules:/app/node_modules
      # your sqlite data
      - sqlite_data:/app/data
    environment:
      - DATABASE_PATH=/app/data/database.db
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["pnpm", "run", "dev-prod"]

volumes:
  sqlite_data:
  node_modules:
