name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-26"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "familymoney-dev"
database_id = "cae6fa2c-e2b2-42eb-bb86-3db743d39829"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1